"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Posts", [
      {
        userId: 2,
        eventId: 2,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-20"),
        updatedAt: new Date("2022-07-20"),
      },
      {
        userId: 3,
        eventId: 3,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-21"),
        updatedAt: new Date("2022-07-21"),
      },
      {
        userId: 4,
        eventId: 3,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-22"),
        updatedAt: new Date("2022-07-22"),
      },
      {
        userId: 5,
        eventId: 3,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-23"),
        updatedAt: new Date("2022-07-23"),
      },
      {
        userId: 2,
        eventId: 4,
        title: "Anyone ever gone without knowing the lineup?",
        body: "I feel like sometimes we get so wrapped up in making each set and planning it perfectly, has anyone ever attended without knowing the schedule and just enjoyed the surprises?",
        createdAt: new Date("2022-07-24"),
        updatedAt: new Date("2022-07-24"),
      },
      {
        userId: 3,
        eventId: 4,
        title: "How much are VIP tickets and are they worth it?",
        body: "Hey y'all. I'm wondering how much does it cost? What does it give that GA doesn't? Is it worth it overall to those who have done it before?",
        createdAt: new Date("2022-07-25"),
        updatedAt: new Date("2022-07-25"),
      },
      {
        userId: 4,
        eventId: 4,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-26"),
        updatedAt: new Date("2022-07-26"),
      },
      {
        userId: 5,
        eventId: 4,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-27"),
        updatedAt: new Date("2022-07-27"),
      },
      {
        userId: 2,
        eventId: 4,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-28"),
        updatedAt: new Date("2022-07-28"),
      },
      {
        userId: 3,
        eventId: 6,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-29"),
        updatedAt: new Date("2022-07-29"),
      },
      {
        userId: 4,
        eventId: 7,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-30"),
        updatedAt: new Date("2022-07-30"),
      },
      {
        userId: 5,
        eventId: 7,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-20"),
        updatedAt: new Date("2022-07-20"),
      },
      {
        userId: 2,
        eventId: 7,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-21"),
        updatedAt: new Date("2022-07-21"),
      },
      {
        userId: 3,
        eventId: 8,
        title: "Anyone ever gone without knowing the lineup?",
        body: "I feel like sometimes we get so wrapped up in making each set and planning it perfectly, has anyone ever attended without knowing the schedule and just enjoyed the surprises?",
        createdAt: new Date("2022-07-22"),
        updatedAt: new Date("2022-07-22"),
      },
      {
        userId: 4,
        eventId: 8,
        title: "How much are VIP tickets and are they worth it?",
        body: "Hey y'all. I'm wondering how much does it cost? What does it give that GA doesn't? Is it worth it overall to those who have done it before?",
        createdAt: new Date("2022-07-23"),
        updatedAt: new Date("2022-07-23"),
      },
      {
        userId: 5,
        eventId: 8,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-24"),
        updatedAt: new Date("2022-07-24"),
      },
      {
        userId: 2,
        eventId: 8,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-25"),
        updatedAt: new Date("2022-07-25"),
      },
      {
        userId: 3,
        eventId: 8,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-26"),
        updatedAt: new Date("2022-07-26"),
      },
      {
        userId: 4,
        eventId: 10,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-27"),
        updatedAt: new Date("2022-07-27"),
      },
      {
        userId: 5,
        eventId: 11,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-28"),
        updatedAt: new Date("2022-07-28"),
      },
      {
        userId: 2,
        eventId: 11,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-29"),
        updatedAt: new Date("2022-07-29"),
      },
      {
        userId: 3,
        eventId: 11,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-30"),
        updatedAt: new Date("2022-07-30"),
      },
      {
        userId: 4,
        eventId: 12,
        title: "Anyone ever gone without knowing the lineup?",
        body: "I feel like sometimes we get so wrapped up in making each set and planning it perfectly, has anyone ever attended without knowing the schedule and just enjoyed the surprises?",
        createdAt: new Date("2022-07-20"),
        updatedAt: new Date("2022-07-20"),
      },
      {
        userId: 5,
        eventId: 12,
        title: "How much are VIP tickets and are they worth it?",
        body: "Hey y'all. I'm wondering how much does it cost? What does it give that GA doesn't? Is it worth it overall to those who have done it before?",
        createdAt: new Date("2022-07-21"),
        updatedAt: new Date("2022-07-21"),
      },
      {
        userId: 2,
        eventId: 12,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-22"),
        updatedAt: new Date("2022-07-22"),
      },
      {
        userId: 3,
        eventId: 12,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-23"),
        updatedAt: new Date("2022-07-23"),
      },
      {
        userId: 4,
        eventId: 12,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-24"),
        updatedAt: new Date("2022-07-24"),
      },
      {
        userId: 5,
        eventId: 14,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-25"),
        updatedAt: new Date("2022-07-25"),
      },
      {
        userId: 1,
        eventId: 15,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-26"),
        updatedAt: new Date("2022-07-26"),
      },
      {
        userId: 3,
        eventId: 15,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-27"),
        updatedAt: new Date("2022-07-27"),
      },
      {
        userId: 4,
        eventId: 15,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-28"),
        updatedAt: new Date("2022-07-28"),
      },
      {
        userId: 5,
        eventId: 16,
        title: "Anyone ever gone without knowing the lineup?",
        body: "I feel like sometimes we get so wrapped up in making each set and planning it perfectly, has anyone ever attended without knowing the schedule and just enjoyed the surprises?",
        createdAt: new Date("2022-07-29"),
        updatedAt: new Date("2022-07-29"),
      },
      {
        userId: 2,
        eventId: 16,
        title: "How much are VIP tickets and are they worth it?",
        body: "Hey y'all. I'm wondering how much does it cost? What does it give that GA doesn't? Is it worth it overall to those who have done it before?",
        createdAt: new Date("2022-07-30"),
        updatedAt: new Date("2022-07-30"),
      },
      {
        userId: 3,
        eventId: 16,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-20"),
        updatedAt: new Date("2022-07-20"),
      },
      {
        userId: 4,
        eventId: 16,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-21"),
        updatedAt: new Date("2022-07-21"),
      },
      {
        userId: 5,
        eventId: 16,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-22"),
        updatedAt: new Date("2022-07-22"),
      },
      {
        userId: 2,
        eventId: 18,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-23"),
        updatedAt: new Date("2022-07-23"),
      },
      {
        userId: 3,
        eventId: 19,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-24"),
        updatedAt: new Date("2022-07-24"),
      },
      {
        userId: 4,
        eventId: 19,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-25"),
        updatedAt: new Date("2022-07-25"),
      },
      {
        userId: 5,
        eventId: 19,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-26"),
        updatedAt: new Date("2022-07-26"),
      },
      {
        userId: 2,
        eventId: 20,
        title: "Anyone ever gone without knowing the lineup?",
        body: "I feel like sometimes we get so wrapped up in making each set and planning it perfectly, has anyone ever attended without knowing the schedule and just enjoyed the surprises?",
        createdAt: new Date("2022-07-27"),
        updatedAt: new Date("2022-07-27"),
      },
      {
        userId: 3,
        eventId: 20,
        title: "How much are VIP tickets and are they worth it?",
        body: "Hey y'all. I'm wondering how much does it cost? What does it give that GA doesn't? Is it worth it overall to those who have done it before?",
        createdAt: new Date("2022-07-28"),
        updatedAt: new Date("2022-07-28"),
      },
      {
        userId: 4,
        eventId: 20,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-29"),
        updatedAt: new Date("2022-07-29"),
      },
      {
        userId: 5,
        eventId: 20,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-30"),
        updatedAt: new Date("2022-07-30"),
      },
      {
        userId: 2,
        eventId: 20,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-20"),
        updatedAt: new Date("2022-07-20"),
      },
      {
        userId: 1,
        eventId: 22,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-21"),
        updatedAt: new Date("2022-07-21"),
      },
      {
        userId: 4,
        eventId: 23,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-22"),
        updatedAt: new Date("2022-07-22"),
      },
      {
        userId: 5,
        eventId: 23,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-23"),
        updatedAt: new Date("2022-07-23"),
      },
      {
        userId: 2,
        eventId: 23,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-24"),
        updatedAt: new Date("2022-07-24"),
      },
      {
        userId: 1,
        eventId: 24,
        title: "Anyone ever gone without knowing the lineup?",
        body: "I feel like sometimes we get so wrapped up in making each set and planning it perfectly, has anyone ever attended without knowing the schedule and just enjoyed the surprises?",
        createdAt: new Date("2022-07-25"),
        updatedAt: new Date("2022-07-25"),
      },
      {
        userId: 3,
        eventId: 24,
        title: "How much are VIP tickets and are they worth it?",
        body: "Hey y'all. I'm wondering how much does it cost? What does it give that GA doesn't? Is it worth it overall to those who have done it before?",
        createdAt: new Date("2022-07-26"),
        updatedAt: new Date("2022-07-26"),
      },
      {
        userId: 4,
        eventId: 24,
        title: "Outfit Ideas",
        body: "This year will be my first time going, and I am wondering what the vibe is like.",
        createdAt: new Date("2022-07-27"),
        updatedAt: new Date("2022-07-27"),
      },
      {
        userId: 5,
        eventId: 24,
        title: "Carpooling to the venue",
        body: "Anyone have space in their car for one more? I can chip in for gas and the parking fee!",
        createdAt: new Date("2022-07-28"),
        updatedAt: new Date("2022-07-28"),
      },
      {
        userId: 2,
        eventId: 24,
        title: "Lineup thoughts?",
        body: "I feel like this year's lineup is so much stronger than last year's.",
        createdAt: new Date("2022-07-29"),
        updatedAt: new Date("2022-07-29"),
      },
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Posts");
  },
};
